name: foto
description: A new Flutter app template

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^1.0.2

  intl: ^0.17.0
  equatable: ^2.0.3
  provider: ^5.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  dio: ^4.0.0
  retrofit: ^2.0.0
  freezed_annotation: ^0.14.2
  flutter_secure_storage: ^4.2.0
  shared_preferences: ^2.0.6
  visibility_detector: ^0.2.0
  qr_flutter: ^4.0.0
  cached_network_image: ^3.0.0
  image_picker: ^0.8.2
  image_gallery_saver: ^1.7.0
  sticky_headers: ^0.2.0
  camerawesome: ^0.3.0+1
  path_provider: ^2.0.2
  package_info: ^2.0.2
  dotted_border: ^2.0.0+1
  share: ^2.0.4
  permission_handler: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  freezed: ^0.14.2
  retrofit_generator: ^2.0.0+1
  url_launcher: ^6.0.9

  # Build Runner command: flutter pub run build_runner build --delete-conflicting-outputs
  # Create App Icon: flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/app_icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/images/
    - assets/images/logo/
    - assets/images/icon/
    - assets/images/sticker/
    - assets/locale/
    - assets/fonts/
    - assets/fonts/Gilroy/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/SVN-Gilroy-Thin.otf
          weight: 100
        - asset: assets/fonts/Gilroy/SVN-Gilroy-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Gilroy/SVN-Gilroy-Xlight.otf
          weight: 200
        - asset: assets/fonts/Gilroy/SVN-Gilroy-XlightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Gilroy/SVN-Gilroy-Light.otf
          weight: 300
        - asset: assets/fonts/Gilroy/SVN-Gilroy-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Gilroy/SVN-Gilroy-Regular.otf
          weight: 400
        - asset: assets/fonts/Gilroy/SVN-Gilroy-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Gilroy/SVN-Gilroy-Medium.otf
          weight: 500
        - asset: assets/fonts/Gilroy/SVN-Gilroy-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Gilroy/SVN-Gilroy-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Gilroy/SVN-Gilroy-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Gilroy/SVN-Gilroy-Bold.otf
          weight: 700
        - asset: assets/fonts/Gilroy/SVN-Gilroy-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Gilroy/SVN-Gilroy-XBold.otf
          weight: 800
        - asset: assets/fonts/Gilroy/SVN-Gilroy-XBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Gilroy/SVN-Gilroy-Heavy.otf
          weight: 900
        - asset: assets/fonts/Gilroy/SVN-Gilroy-HeavyItalic.otf
          weight: 900
          style: italic

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.otf
  #       - asset: fonts/Schyler-Italic.otf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.otf
  #       - asset: fonts/TrajanPro_Bold.otf
  #         weight: 700
